# GET ALL USERS
GET http://localhost:5000/users/
###

# GET A SINGLE USER
GET http://localhost:5000/users/1
###

# REGISTER A USER
POST http://localhost:5000/register
content-type: application/json

{
    "email":"mtitos@email.com",
    "password":"mtiTosTt"
}
###

# SIGN IN
POST http://localhost:5000/login
content-type: application/json

{
    "email":"thikios@email.com",
    "password":"tshepiThinki"
}
###

# GET ALL BOOKINGS
http://localhost:5000/bookings/
###

# GET ALL BOOKINGS FOR A USER
http://localhost:5000/users/1/bookings

###
http://localhost:5000/listing/

###
# POSt http://localhost:5000/posts
# content-type: application/json

# {
#     "title": "airbnb-clone",
#     "author": "siyabonga"
# }